import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ShoppingListSheet extends StatefulWidget {
  final Map<String, List<String>> shoppingList;
  final ScrollController scrollController;

  const ShoppingListSheet({
    super.key,
    required this.shoppingList,
    required this.scrollController,
  });

  @override
  State<ShoppingListSheet> createState() => _ShoppingListSheetState();
}

class _ShoppingListSheetState extends State<ShoppingListSheet> {
  // Stores unique keys for checked items to handle UI state
  final Set<String> _checkedItems = {};

  void _toggleItem(String category, String item) {
    final key = "$category::$item";
    setState(() {
      if (_checkedItems.contains(key)) {
        _checkedItems.remove(key);
      } else {
        _checkedItems.add(key);
      }
    });
  }

  /// Helper to pick an icon based on category name
  IconData _getCategoryIcon(String category) {
    final cat = category.toLowerCase();
    if (cat.contains('produce') || cat.contains('fruit') || cat.contains('veg')) {
      return Icons.eco_outlined;
    } else if (cat.contains('meat') || cat.contains('seafood') || cat.contains('fish')) {
      return Icons.restaurant_menu;
    } else if (cat.contains('dairy') || cat.contains('egg') || cat.contains('cheese')) {
      return Icons.egg_outlined;
    } else if (cat.contains('pantry') || cat.contains('spice') || cat.contains('oil')) {
      return Icons.kitchen;
    } else if (cat.contains('grain') || cat.contains('bread') || cat.contains('pasta')) {
      return Icons.bakery_dining_outlined;
    }
    return Icons.shopping_basket_outlined;
  }

  String _cleanText(String text) {
    return text.replaceAll(RegExp(r'[^\x00-\x7F]'), '');
  }

  Future<void> _generatePdf(BuildContext context) async {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text("Preparing PDF..."), duration: Duration(seconds: 1)),
    );

    try {
      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("My Shopping List", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text("Generated by NutriWise", style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey500)),
                  ]
                )
              ),
              pw.SizedBox(height: 20),
              ...widget.shoppingList.entries.map((entry) {
                final category = _cleanText(entry.key);
                final items = entry.value.map((i) => _cleanText(i)).toList();
                if (items.isEmpty) return pw.Container();

                return pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Container(
                      width: double.infinity,
                      padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 0),
                      decoration: const pw.BoxDecoration(
                        border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300, width: 1))
                      ),
                      child: pw.Text(
                        category.toUpperCase(),
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14, color: PdfColors.blueGrey800),
                      ),
                    ),
                    pw.SizedBox(height: 8),
                    ...items.map(
                      (item) => pw.Padding(
                        padding: const pw.EdgeInsets.only(left: 0, bottom: 6),
                        child: pw.Row(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Container(
                              width: 12,
                              height: 12,
                              margin: const pw.EdgeInsets.only(top: 2, right: 8),
                              decoration: pw.BoxDecoration(
                                border: pw.Border.all(color: PdfColors.grey400),
                                shape: pw.BoxShape.rectangle,
                              ),
                            ),
                            pw.Expanded(child: pw.Text(item, style: const pw.TextStyle(fontSize: 12))),
                          ],
                        ),
                      ),
                    ),
                    pw.SizedBox(height: 15),
                  ],
                );
              }),
            ];
          },
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: 'NutriWise_Shopping_List',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error generating PDF: $e"), backgroundColor: Colors.red),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // Calculate Progress
    int totalItems = 0;
    widget.shoppingList.values.forEach((l) => totalItems += l.length);
    int checkedCount = _checkedItems.length;
    double progress = totalItems == 0 ? 0 : checkedCount / totalItems;

    return Scaffold(
      backgroundColor: Colors.transparent,
      // Floating Action Button for PDF
      floatingActionButton: Padding(
        padding: const EdgeInsets.only(bottom: 20),
        child: FloatingActionButton.extended(
          onPressed: () => _generatePdf(context),
          backgroundColor: Colors.orange,
          foregroundColor: Colors.white,
          elevation: 4,
          icon: const Icon(Icons.picture_as_pdf_rounded),
          label: const Text("Download PDF"),
        ),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      body: ListView(
        controller: widget.scrollController,
        padding: const EdgeInsets.fromLTRB(24, 24, 24, 100), // Extra bottom padding for FAB
        children: [
          // 1. Drag Handle
          Center(
            child: Container(
              width: 40,
              height: 5,
              decoration: BoxDecoration(
                color: Colors.grey[300],
                borderRadius: BorderRadius.circular(10),
              ),
            ),
          ),
          const SizedBox(height: 24),

          // 2. Header & Progress
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    "Shopping List",
                    style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                          color: Colors.black87,
                        ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    "$checkedCount of $totalItems items collected",
                    style: TextStyle(color: Colors.grey.shade600, fontSize: 14),
                  ),
                ],
              ),
              CircularProgressIndicator(
                value: progress,
                backgroundColor: Colors.orange.shade100,
                color: Colors.orange,
                strokeWidth: 6,
              ),
            ],
          ),
          const SizedBox(height: 24),

          if (widget.shoppingList.isEmpty)
            Container(
              padding: const EdgeInsets.all(32),
              alignment: Alignment.center,
              decoration: BoxDecoration(
                color: Colors.grey.shade50,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: Colors.grey.shade200),
              ),
              child: Column(
                children: [
                  Icon(Icons.shopping_cart_outlined, size: 48, color: Colors.grey.shade400),
                  const SizedBox(height: 16),
                  Text("Your list is empty", style: TextStyle(color: Colors.grey.shade600)),
                ],
              ),
            ),

          // 3. Categories List
          ...widget.shoppingList.entries.map((entry) {
            return _buildCategorySection(entry.key, entry.value);
          }),
        ],
      ),
    );
  }

  Widget _buildCategorySection(String category, List<String> items) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Category Header
          Row(
            children: [
              Icon(_getCategoryIcon(category), size: 20, color: Colors.orange),
              const SizedBox(width: 8),
              Text(
                category,
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.black87,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          
          // Items Card
          Container(
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.03),
                  blurRadius: 10,
                  offset: const Offset(0, 4),
                ),
              ],
              border: Border.all(color: Colors.grey.shade100),
            ),
            child: Column(
              children: items.asMap().entries.map((entry) {
                final index = entry.key;
                final item = entry.value;
                final isChecked = _checkedItems.contains("$category::$item");
                final isLast = index == items.length - 1;

                return Column(
                  children: [
                    InkWell(
                      onTap: () => _toggleItem(category, item),
                      borderRadius: BorderRadius.vertical(
                        top: index == 0 ? const Radius.circular(16) : Radius.zero,
                        bottom: isLast ? const Radius.circular(16) : Radius.zero,
                      ),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                        child: Row(
                          children: [
                            // Custom Checkbox
                            AnimatedContainer(
                              duration: const Duration(milliseconds: 200),
                              width: 24,
                              height: 24,
                              decoration: BoxDecoration(
                                color: isChecked ? Colors.orange : Colors.white,
                                borderRadius: BorderRadius.circular(8),
                                border: Border.all(
                                  color: isChecked ? Colors.orange : Colors.grey.shade300,
                                  width: 2,
                                ),
                              ),
                              child: isChecked
                                  ? const Icon(Icons.check, size: 16, color: Colors.white)
                                  : null,
                            ),
                            const SizedBox(width: 16),
                            // Item Text
                            Expanded(
                              child: Text(
                                item,
                                style: TextStyle(
                                  fontSize: 15,
                                  color: isChecked ? Colors.grey.shade400 : Colors.black87,
                                  decoration: isChecked ? TextDecoration.lineThrough : null,
                                  decorationColor: Colors.orange,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    if (!isLast)
                      Divider(height: 1, thickness: 1, color: Colors.grey.shade100, indent: 56),
                  ],
                );
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }
}