import 'package:flutter/material.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class ShoppingListSheet extends StatelessWidget {
  final Map<String, List<String>> shoppingList;
  final ScrollController scrollController;

  const ShoppingListSheet({
    super.key,
    required this.shoppingList,
    required this.scrollController,
  });

  /// Helper to clean text (removes emojis or characters that might break standard PDF fonts)
  String _cleanText(String text) {
    return text.replaceAll(RegExp(r'[^\x00-\x7F]'), '');
  }

  /// ✅ NEW: PDF Generation Logic
  Future<void> _generatePdf(BuildContext context) async {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text("Preparing PDF..."), duration: Duration(seconds: 1)),
    );

    try {
      final pdf = pw.Document();

      // Build the PDF content
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (pw.Context context) {
            return [
              // Header
              pw.Header(
                level: 0,
                child: pw.Text("My Shopping List",
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text(
                "Here are the ingredients needed for your upcoming meal plan.",
                style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
              ),
              pw.SizedBox(height: 20),

              // Dynamic Categories
              ...shoppingList.entries.map((entry) {
                final category = _cleanText(entry.key);
                final items = entry.value.map((i) => _cleanText(i)).toList();

                if (items.isEmpty) return pw.Container();

                return pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Container(
                      width: double.infinity,
                      padding: const pw.EdgeInsets.symmetric(vertical: 5, horizontal: 10),
                      color: PdfColors.grey200,
                      child: pw.Text(
                        category.toUpperCase(),
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 12),
                      ),
                    ),
                    pw.SizedBox(height: 10),
                    ...items.map(
                      (item) => pw.Padding(
                        padding: const pw.EdgeInsets.only(left: 10, bottom: 5),
                        child: pw.Row(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Container(
                              width: 4,
                              height: 4,
                              margin: const pw.EdgeInsets.only(top: 5, right: 5),
                              decoration: const pw.BoxDecoration(
                                color: PdfColors.black,
                                shape: pw.BoxShape.circle,
                              ),
                            ),
                            pw.Expanded(
                              child: pw.Text(item, style: const pw.TextStyle(fontSize: 14)),
                            ),
                          ],
                        ),
                      ),
                    ),
                    pw.SizedBox(height: 15),
                  ],
                );
              }),
              
              pw.Divider(color: PdfColors.grey400),
              pw.Center(
                child: pw.Text(
                  "Generated by NutriWise AI",
                  style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
                ),
              ),
            ];
          },
        ),
      );

      // Open Print/Share Dialog
      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
        name: 'My_Shopping_List',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Error generating PDF: $e"), backgroundColor: Colors.red),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return ListView(
      controller: scrollController,
      padding: const EdgeInsets.all(24),
      children: [
        // 1. Drag Handle
        Center(
          child: Container(
            width: 40,
            height: 5,
            decoration: BoxDecoration(
              color: Colors.grey[300],
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
        const SizedBox(height: 20),

        // 2. Header
        Row(
          children: [
            Icon(Icons.shopping_bag_outlined, color: Colors.orange.shade600, size: 28),
            const SizedBox(width: 12),
            Flexible(
              child: Text(
                "Your Shopping List",
                style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                      fontWeight: FontWeight.bold,
                      color: Colors.black87,
                    ),
              ),
            ),
          ],
        ),
        const SizedBox(height: 8),
        Text(
          "Consolidated ingredients for your meal plan.",
          style: TextStyle(color: Colors.grey.shade600, fontSize: 14),
        ),
        const SizedBox(height: 24),

        if (shoppingList.isEmpty)
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.grey.shade50,
              borderRadius: BorderRadius.circular(16),
            ),
            child: const Center(child: Text("No ingredients found to list.")),
          ),

        // 3. List Content
        ...shoppingList.entries.map((entry) {
          return _buildCategorySection(context, entry.key, entry.value);
        }),

        const SizedBox(height: 32),

        // 4. ✅ PDF Download Button
        SizedBox(
          width: double.infinity,
          child: ElevatedButton.icon(
            onPressed: () => _generatePdf(context),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.orange,
              foregroundColor: Colors.white,
              elevation: 2,
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            icon: const Icon(Icons.picture_as_pdf_rounded),
            label: const Text(
              "Download as PDF",
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
          ),
        ),

        const SizedBox(height: 40), // Bottom padding
      ],
    );
  }

  Widget _buildCategorySection(BuildContext context, String category, List<String> items) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(category,
              style: Theme.of(context)
                  .textTheme
                  .titleMedium
                  ?.copyWith(fontWeight: FontWeight.bold, color: Colors.black87)),
          const SizedBox(height: 12),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.orange.shade50,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: Colors.orange.shade100),
            ),
            child: Column(
              children: items.map((item) => _buildItemRow(item)).toList(),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildItemRow(String item) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 2),
            child: CircleAvatar(
              backgroundColor: Colors.orange.withOpacity(0.8),
              radius: 8,
              child: const Icon(Icons.check, size: 10, color: Colors.white),
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Text(item,
                style: const TextStyle(fontSize: 15, height: 1.3, color: Colors.black87)),
          ),
        ],
      ),
    );
  }
}